version: "3"

tasks:
  dbdocs:
    desc: Build database documentation
    cmds:
      - dbdocs build docs/database.dbml
  migrateup:
    desc: Migrate up the database schema
    cmds:
      - migrate -database ${POSTGRESQL_URL} -path internal/database/migrations up
  migratedown:
    desc: Migrate down the database schema
    cmds:
      - migrate -database ${POSTGRESQL_URL} -path internal/database/migrations down
  lint:
    desc: Check code for programmatic and stylistic errors
    cmds:
      - golangci-lint run
  build:
    desc: Compile code
    cmds:
      - go build -o bin/app cmd/main.go
  run:
    desc: Run compiled compiled
    deps: [build]
    cmds:
      - ./bin/app
