CREATE TABLE IF NOT EXISTS "loan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "book_id" int NOT NULL,
  "is_returned" boolean NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX ON "loan" ("user_id");

CREATE INDEX ON "loan" ("user_id", "book_id");

ALTER TABLE "loan" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "loan" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id");